---
# tasks file for jw74.kvmHost
- name: install KVM and tools
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
      - qemu-kvm
      - virtinst
      - libvirt-bin
      - virt-manager 

- name: copy my dhcpkonfig
  template:
    src: default.xml.j2
    dest: /etc/libvirt/qemu/networks/default.xml
    owner: root
    group: root
    mode: 0600
...
