---
# tasks file for jw74.kvmHost
- name: install KVM and tools
  apt:
    name: ['qemu-kvm','libvirt-daemon', 'virt-manager']
    state: latest

- name: generating my dhcpkonfig
  template:
    src: default.xml.j2
    dest: /etc/libvirt/qemu/networks/default.xml
    owner: root
    group: root
    mode: 0600

- name: Start service libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes
...
