---
roleVarTerraformDownload: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
roleVarTerraformDownloadChecksum: sha256:be99da1439a60942b8d23f63eba1ea05ff42160744116e84f46fc24f1a8011b6
roleVarTerraformProviderLibvirtDownload: https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v0.6.2/terraform-provider-libvirt-0.6.2+git.1585292411.8cbe9ad0.Ubuntu_18.04.amd64.tar.gz
...
