---
- name: creating subdirectory for terraform provider
  file:
    path: "{{ item }}"
    mode: 0700
    recurse: yes
    owner: "{{ ansible_user_id }}"
  with_items:
    - "{{ ansible_user_dir }}/.terraform.d/plugins/"
    - "{{ ansible_user_dir }}/bin/"

- name: creating temporary file dir
  file:
    path: "{{ ansible_user_dir }}/workspace/playbooks/roles/jw74.installTerraform/files/"
    mode: 0775
    recurse: yes
    owner: "{{ ansible_user_id }}"

- name: Download terraform with check (sha256) and terraform-provider-libvirt
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dst }}"
    checksum: "{{ item.cks | default(omit) }}"
    owner: "{{ ansible_user_id }}" 
    mode: 0600
  with_items:
    - { src: "{{ roleVarTerraformDownload }}", dst: "{{ ansible_user_dir }}/workspace/playbooks/roles/jw74.installTerraform/files/{{ roleVarTerraformDownload | basename }}", cks: "{{ roleVarTerraformDownloadChecksum }}" }
    - { src: "{{ roleVarTerraformProviderLibvirtDownload }}", dst: "{{ ansible_user_dir }}/workspace/playbooks/roles/jw74.installTerraform/files/{{ roleVarTerraformProviderLibvirtDownload | basename }}" }

- name: Extract terraform and terraform-provider-libvirt
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    mode: 0700
    owner: "{{ ansible_user_id }}"
  with_items:
    - { src: "{{ ansible_user_dir }}/workspace/playbooks/roles/jw74.installTerraform/files/{{ roleVarTerraformDownload | basename }}", dst: "{{ ansible_user_dir }}/bin/" }
    - { src: "{{ ansible_user_dir }}/workspace/playbooks/roles/jw74.installTerraform/files/{{ roleVarTerraformProviderLibvirtDownload | basename }}", dst: "{{ ansible_user_dir }}/.terraform.d/plugins/" }

- name: deleting zipfile of terraform and terraform-provider-libvirt
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_user_dir }}/workspace/playbooks/roles/jw74.installTerraform/files/{{ roleVarTerraformDownload | basename }}"
    - "{{ ansible_user_dir }}/workspace/playbooks/roles/jw74.installTerraform/files/{{ roleVarTerraformProviderLibvirtDownload | basename }}"
...
