---
# tasks file for jw74.ansibleHost
- name: installing ansible-lint, ansible-vault
  pip:
    name: ['pip', 'ansible', 'ansible-lint', 'ansible-vault']
    state: latest

- name: generate logrotate, ansible.cfg, sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: "{{ item.user }}"
    mode: 0600
  become: yes
  with_items:
    - { src: ansible_logrotate.j2, dst: /etc/logrotate.d/ansible, user: root }
    - { src: ansible.j2.cfg, dst: "/home/{{ ansible_user_id }}/.ansible.cfg", user: "{{ ansible_user_id }}" }
    - { src: user.j2.sudo, dst: "/etc/sudoers.d/{{ ansible_user_id }}", user: root }

- name: creating needed dirs
  file:
    path: "/home/{{ ansible_user_id }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0700
  with_items:
    - var
    - var/log
    - .ansible
    - .ansible/tmp
...
