---
# tasks file for jw74.ansibleHost
- name: installing ansible-lint, ansible-vault
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - ansible
    - ansible-lint
    - ansible-vault

- name: create group for ansiblemaster
  group:
    name: "{{ taskAnsibleGroup }}"
    gid: "{{ taskAnsibleGid }}"
    state: present

- name: create user for ansible host
  user:
    name: "{{ taskAnsibleUser }}"
    comment: "this ist the user of wich alle playbooks getting startet or executed"
    uid: "{{ taskAnsibleUid }}"
    group: "{{ taskAnsibleGid }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: copy ansible.cfg
  copy:
    src: ansible.cfg
    dest: "/home/{{ taskAnsibleUser }}/.ansible.cfg"
    owner: "{{ taskAnsibleUser }}"
    group: "{{ taskAnsibleGroup }}"
    mode: 0600

- name: creating sudo privilege for ansible
  copy:
    src: "{{ taskAnsibleUser }}.sudo"
    dest: "/etc/sudoers.d/{{ taskAnsibleUser }}"
    owner: root
    group: root
    mode: 0600

- name: creating needed dirs
  file:
    path: "/home/{{ taskAnsibleUser }}/{{ item }}"
    state: directory
    owner: "{{ taskAnsibleUser }}"
    group: "{{ taskAnsibleGroup }}"
    mode: 0700
  with_items:
    - var
    - var/log
    - .ansible
    - .ansible/tmp
...
